### PR TITLE
Liberty: Fix `bit_...` fields in bus definitions

### LINKED ISSUE #6: Liberty files: `bit_from`/... illegaly given as floats
Hi everyone,

I've been noticing that cadence tools have problems with these constructs in the liberty files, specifically with the `bit_...` fields not being given as integers.

```
    type ("bus4") {
[...]
        bit_from : 3.0000000000;
        bit_to : 0.0000000000;
        bit_width : 4.0000000000;
[...]
    }
    type ("bus8") {
[...]
    }
    type ("bus16") {
[...]
    }
```

The Liberty Specification specifies these fields to be integers so I think we should probably adapt that, even though the open soure tools can handle the floats.

### PR DESCRIPTION
**Pull request by ubfx**
The Liberty User Guide specifies these fields to be integers, but they are currently given as floats in the .lib-files, leading to problems with some tools.

Example before fix: 
```
type ("bus8") {
        base_type : "array";
        bit_from : 7.0000000000;
        bit_to : 0.0000000000;
        bit_width :  8.000000000;
[...]
```

Fix https://github.com/efabless/skywater-pdk-libs-sky130_fd_sc_hdll/issues/6

### CODE REVIEW

**Comment by ubfx** [comment]
I also checked all other logic libraries, and this (`hdll`) seems to be the only one where this is a problem. All others are already using integers.

**Comment by RTimothyEdwards** [comment]
I can work on this after I merge the pull request for the cut layer issue, unless you have a pull request for this waiting.

**Comment by RTimothyEdwards** [comment]
Sorry, I see the pull request.  Somehow until I refreshed my browser I didn't see any files changed.  So I'll go ahead and review.

**Review by RTimothyEdwards — APPROVED** [review]
All looks good to me.

**Pull request merged**
